version: 1.3.{build}
image:
- Visual Studio 2017

 
init:

 
install:
- cmd: echo %APPVEYOR_BUILD_FOLDER%

- cmd: git submodule update --init
    
- cmd: cd %APPVEYOR_BUILD_FOLDER%\libusb
    
- cmd:   git apply ..\msvc\0001-Static-link-C-library.patch
    
- cmd:    cd ..
 


build_script:

- cmd: msbuild %APPVEYOR_BUILD_FOLDER%/msvc/uuu.sln /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

- cmd: cov-build --dir cov-int msbuild %APPVEYOR_BUILD_FOLDER%/msvc/uuu-static-link.sln /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

- cmd: 7z a -tzip mfg.zip cov-int

- cmd: curl --form token=VU2hes6TFBF6tFVjQu621A --form email=weilin.cao@nxp.com --form file=@mfg.zip --form version="automation test(static)"  --form description="testing coverity automation" https://scan.coverity.com/builds?project=NXPmicro+mfgtools

- cmd: dir build-log.txt /s /p

- cmd: if exist %APPVEYOR_BUILD_FOLDER%\x64\release\lib\uuu.exe  cp %APPVEYOR_BUILD_FOLDER%\x64\release\lib\uuu.exe  %APPVEYOR_BUILD_FOLDER%\uuu.exe
   


